prplmesh_utils.sh: Retrying mechanism
When adding instances to the process monitor, do not fail right away,
but try to add them again

PPM-3129

Suggested-by: Maarten De Decker <maarten.dedecker@mind.be>
Signed-off-by: Denys Stolbov <d.stolbov@inango-systems.com>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -351,9 +351,12 @@ usage() {
     echo "usage: $(basename "$0") {start|stop|restart|status|roll_logs} [-hvpmdCD]"
 }
 
+check_processmonitor_entry() {
+    ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_$1'].?" | grep -Eq "No data found|ERROR"
+}
+
 add_processmonitor_entry() {
-    (ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_$1'].?" | grep -q "No data found") &&
-    echo "Adding processmonitor entry for PrplMesh $1" &&
+    echo "Adding ProcessMonitor entry for prplMesh $1" &&
     ba-cli -l "ProcessMonitor.Test.+(
         Name='prplmesh', 
         Type='Process', 
@@ -361,17 +364,51 @@ add_processmonitor_entry() {
         MaxFailNum=0, 
         FailAction='RESTART', 
         TestInterval=5
-        )"
+        )" > /dev/null
+}
+
+remove_processmonitor_entry() {
+    echo "Removing ProcessMonitor entry for prplMesh $1" &&
+    (ba-cli -l "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_$1'].-" > /dev/null || true)
+    check_processmonitor_entry "$1"
+    statusCode=$?
+    if [ $statusCode -eq 0 ]; then
+        echo "ProcessMonitor entry has been removed successfully"
+    else
+        echo "Failed to remove the ProcessMonitor entry"
+    fi
 }
 
 remove_processmonitor_entries() {
-    (ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_agent'].?" | grep -q "prplmesh") &&
-    echo "Removing processmonitor entry for PrplMesh Agent" &&
-    ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_agent'].-"
+    (check_processmonitor_entry "agent") ||
+    remove_processmonitor_entry "agent"
 
-    (ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_controller'].?" | grep -q "prplmesh") &&
-    echo "Removing processmonitor entry for PrplMesh Controller" &&
-    ba-cli "ProcessMonitor.Test.[Subject=='/tmp/beerocks/pid/beerocks_controller'].-"
+    (check_processmonitor_entry "controller") ||
+    remove_processmonitor_entry "controller"
+}
+
+add_processmonitor() {
+    retries=10
+    statusCode=0
+
+    echo "Checking if ProcessMonitor entry for '$1' exists..."
+    if ! check_processmonitor_entry "$1"; then
+        echo "ProcessMonitor entry for '$1' already exists. Skipping..."
+    else
+        while [ $retries -gt 0 ] && [ $statusCode -ne 1 ]; do
+            echo "Trying to add ProcessMonitor entry for '$1'..."
+            add_processmonitor_entry "$1"
+            sleep 1
+            check_processmonitor_entry "$1"
+            statusCode=$?
+            if [ $statusCode -eq 1 ]; then
+                echo "ProcessMonitor entry has been added successfully"
+            else
+                echo "Failed to add the ProcessMonitor entry"
+            fi
+            retries=$((retries - 1))
+        done
+    fi
 }
 
 main() {
@@ -407,10 +444,11 @@ main() {
         "start")
             start_function
             if [ "$PRPLMESH_MODE" = "CA" ] || [ "$PRPLMESH_MODE" = "C" ]; then
-                add_processmonitor_entry "controller"
+                add_processmonitor "controller"
             fi
+
             if [ "$PRPLMESH_MODE" = "CA" ] || [ "$PRPLMESH_MODE" = "A" ]; then
-                add_processmonitor_entry "agent"
+                add_processmonitor "agent"
             fi
             ;;
         "start_wait")
